target: /Users/du.lei/Documents/work/1-代码/workspace/mybatis-gen/src/main/java/
items:
  -
    pkg: com.chinaredstar.property
    domain: Property
    primaryKeyField: propertyId
    uriPath: /property
    dao: com.chinaredstar.property